services:
  nginx:
    image: nginx:latest
    ports:
      - "3000:80"
    volumes:
      - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - web

  web:
    image: miapp_web:latest #para el swarm
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
    working_dir: /app
    command: node src/server.js
    deploy:
      replicas: 3
      resources:  #inicio escalamiento vertical
        limits:
          cpus: "1.00"  #1cpu por contenedor
          memory: "512M"  #limita a 512 MB de RAM por contenedor
        reservations:
          cpus: "0.50"  #Reserva minima garantizada de CPU
          memory: "256M"  #Reserva mimina garantizada de RAM